kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
- kind: User
  name: whoami
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
